package graphical.editor.v2.shapes;

public class Ellipse extends Shape {
    public Ellipse(int xCoordinate, int yCoordinate) {
        super(xCoordinate, yCoordinate, "Ellipse", """
                            ....................                              
                    ........                    ........                        
              ......                                    ......                  
        ......                                                ......            
      ..                                                            ..          
    ..                                                                ..        
  ..                                                                    ..      
  ..                                                                    .. 
  ..                                                                    ..
  ..                                                                    ..  
    ..                                                                ..        
      ..                                                            ..    
        ......                                                ......  
              ......                                    ......            
                    ........                    ........            
                            ....................  
                            
                            """);
    }
}
